services:
   web:
     image: ${DOCKER_REGISTRY-}web
     build:
       context: .
       dockerfile: Web/Opss.PrimaryAuthorityRegister.Web/Dockerfile
   api:
     image: ${DOCKER_REGISTRY-}api
     build:
       context: .
       dockerfile: Api/Opss.PrimaryAuthorityRegister.Core.Api/Dockerfile