name: CI for OPSS PAR V4 Application

on:
  pull_request:
    branches:
      - develop
env:
  SLN_PATH: ./Opss.PrimaryAuthorityRegister.sln
  COVERLET_PATH: coverage

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore $SLN_PATH

      # Build the solution
      - name: Build the solution
        run: dotnet build $SLN_PATH --no-restore --configuration Release

      # Run tests
      - name: Run tests
        run: dotnet test $SLN_PATH --configuration Release --no-build --verbosity normal  --collect:"XPlat Code Coverage"  --results-directory ./$COVERLET_PATH

      # Remove 'empty' coverage files - they cause the CodeCoverageSummary action to fail
      - name: Remove empty coverage files
        run: find ./$COVERLET_PATH -type f -exec sh -c 'for f in "$@"; do grep -l "<sources />" "$f" && rm -f -- "$f"; done' _ {} + || true

      # check files
      - name: Check files
        run: find ./$COVERLET_PATH -type f

      # check glob
      - name: Check glob
        run: shopt -s globstar; printf %s\\n ./$COVERLET_PATH/**/coverage.cobertura.xml

      # Consolidate coverage files
      - name: Consolidate coverage files
        run: |
          dotnet tool install -g dotnet-coverage
          dotnet-coverage merge ./$COVERLET_PATH/**/coverage.cobertura.xml -o $COVERLET_PATH/coverage.cobertura.xml -f cobertura --remove-input-files
          ls -l ./$COVERLET_PATH

      # Code Coverage Report
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./$COVERLET_PATH/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      # Add Coverage PR Comment
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
