name: CI for OPSS PAR V4 Application

on:
  pull_request:
    branches:
      - develop
env:
  SLN_PATH: ./Opss.PrimaryAuthorityRegister.sln
  COVERLET_PATH: coverage

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore $SLN_PATH

      # Build the solution
      - name: Build the solution
        run: dotnet build $SLN_PATH --no-restore --configuration Release

      # Run tests
      - name: Run tests
        run: dotnet test $SLN_PATH --configuration Release --no-build --verbosity normal  --collect:"XPlat Code Coverage" --settings Coverlet.runsettings  --results-directory ./$COVERLET_PATH

      # Remove 'empty' coverage files - they cause the CodeCoverageSummary action to fail
      - name: Remove empty coverage files
        run: find ./$COVERLET_PATH -type f -exec sh -c 'for f in "$@"; do grep -l "<sources />" "$f" && rm -f -- "$f"; done' _ {} + || true

      # Consolidate coverage files
      - name: Consolidate coverage files
        run: |
          dotnet tool install -g dotnet-coverage
          dotnet-coverage merge ./$COVERLET_PATH/**/coverage.cobertura.xml -o $COVERLET_PATH/coverage.cobertura.xml -f cobertura --remove-input-files
          ls -l $COVERLET_PATH

      # Code Coverage Report
      - name: Produce the coverage report
        uses: insightsengineering/coverage-action@v2
        with:
          path: ./$COVERLET_PATH/coverage.cobertura.xml
          threshold: 80.0
          fail: true
          publish: true
          diff: true
          diff-branch: develop
          diff-storage: _xml_coverage_reports
          coverage-summary-title: "Code Coverage Summary"
