name: CI for OPSS PAR V4 Application

on:
  pull_request:
    branches:
      - develop
env:
  SLN_PATH: ./Opss.PrimaryAuthorityRegister.sln
  COVERLET_PATH: coverage

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore $SLN_PATH

      # Build the solution
      - name: Build the solution
        run: dotnet build $SLN_PATH --no-restore --configuration Release

      # Run tests
      - name: Run tests
        run: dotnet test $SLN_PATH --configuration Release --no-build --verbosity normal  --collect:"XPlat Code Coverage"  --results-directory ./$COVERLET_PATH
